name: ucc_quiz_portal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.2.2
  objectbox: ^2.1.0
  path_provider: ^2.0.15
  objectbox_flutter_libs: any
  path: ^1.8.3
  uuid: ^3.0.7
  logger: ^2.0.1
  provider: ^6.0.5
  airplane_mode_checker: ^2.0.0
  camera: ^0.10.5+5
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.0
  cloud_firestore: 4.12.0
  modal_bottom_sheet: ^3.0.0-pre
  google_fonts: ^6.1.0
  video_compress: ^3.1.2
  connectivity: ^3.0.6
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  objectbox_generator: any
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/anim/
